name: Dast Analyze With Arachni
on:
    workflow_run:
        workflows: [Snyk ANALYZE]
        types:
        - completed
jobs:
    dast:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

