name: Snyk ANALYZE
on:
  push:
    branches:
      - dev
jobs:
  security:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SNYK_TOKEN
        run: echo ${SNYK_TOKEN}
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        #continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          #command: auth
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
