name: Snyk ANALYZE
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
        statuses: write
    steps:
      - uses: actions/checkout@master
      - name: Authenticate Synk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
